package com.streaming.analytics.servlet;

import java.io.*;
import jakarta.servlet.http.*;
import jakarta.servlet.annotation.*;

@WebServlet(name = "dashboardServlet", value = "/dashboard")
public class DashboardServlet extends HttpServlet {
    private String message;

    public void init() {
        message = "Streaming Analytics Dashboard";
    }

    public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
        response.setContentType("text/html");

        PrintWriter out = response.getWriter();
        out.println("<!DOCTYPE html>");
        out.println("<html lang='fr'>");
        out.println("<head>");
        out.println("    <meta charset='UTF-8'>");
        out.println("    <meta name='viewport' content='width=device-width, initial-scale=1.0'>");
        out.println("    <title>Streaming Analytics Dashboard - Entry</title>");
        out.println("    <style>");
        out.println("        * {");
        out.println("            margin: 0;");
        out.println("            padding: 0;");
        out.println("            box-sizing: border-box;");
        out.println("        }");
        out.println("        ");
        out.println("        body {");
        out.println("            font-family: 'Inter', 'Segoe UI', system-ui, -apple-system, sans-serif;");
        out.println("            background: linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%);");
        out.println("            color: #e8eaf6;");
        out.println("            margin: 0;");
        out.println("            padding: 20px;");
        out.println("            min-height: 100vh;");
        out.println("            position: relative;");
        out.println("        }");
        out.println("        ");
        out.println("        body::before {");
        out.println("            content: '';");
        out.println("            position: absolute;");
        out.println("            top: 0;");
        out.println("            left: 0;");
        out.println("            right: 0;");
        out.println("            bottom: 0;");
        out.println("            background: radial-gradient(circle at 20% 80%, rgba(168, 85, 247, 0.15) 0%, transparent 50%),");
        out.println("                        radial-gradient(circle at 80% 20%, rgba(59, 130, 246, 0.15) 0%, transparent 50%);");
        out.println("            pointer-events: none;");
        out.println("        }");
        out.println("        ");
        out.println("        .retro-container {");
        out.println("            max-width: 900px;");
        out.println("            margin: 0 auto;");
        out.println("            background: rgba(30, 27, 75, 0.85);");
        out.println("            border: 1px solid rgba(168, 85, 247, 0.2);");
        out.println("            border-radius: 24px;");
        out.println("            padding: 50px;");
        out.println("            box-shadow: 0 25px 50px rgba(0, 0, 0, 0.3), 0 0 80px rgba(168, 85, 247, 0.1), inset 0 1px 0 rgba(255, 255, 255, 0.1);");
        out.println("            backdrop-filter: blur(30px);");
        out.println("            position: relative;");
        out.println("            z-index: 1;");
        out.println("        }");
        out.println("        ");
        out.println("        h1 {");
        out.println("            text-align: center;");
        out.println("            font-size: 3.2em;");
        out.println("            font-weight: 800;");
        out.println("            margin-bottom: 30px;");
        out.println("            background: linear-gradient(135deg, #a855f7 0%, #ec4899 50%, #06b6d4 100%);");
        out.println("            -webkit-background-clip: text;");
        out.println("            -webkit-text-fill-color: transparent;");
        out.println("            background-clip: text;");
        out.println("            letter-spacing: -1px;");
        out.println("        }");
        out.println("        ");
        out.println("        h2 {");
        out.println("            font-size: 2em;");
        out.println("            background: linear-gradient(135deg, #e9d5ff 0%, #fae8ff 100%);");
        out.println("            -webkit-background-clip: text;");
        out.println("            -webkit-text-fill-color: transparent;");
        out.println("            background-clip: text;");
        out.println("            font-weight: 700;");
        out.println("        }");
        out.println("        ");
        out.println("        .welcome-text {");
        out.println("            text-align: center;");
        out.println("            font-size: 1.2em;");
        out.println("            margin: 20px 0;");
        out.println("            color: #c4b5fd;");
        out.println("            line-height: 1.7;");
        out.println("        }");
        out.println("        ");
        out.println("        .retro-button {");
        out.println("            display: inline-block;");
        out.println("            background: linear-gradient(135deg, #a855f7 0%, #ec4899 100%);");
        out.println("            color: white;");
        out.println("            padding: 18px 45px;");
        out.println("            text-decoration: none;");
        out.println("            border: none;");
        out.println("            border-radius: 12px;");
        out.println("            font-size: 1.1em;");
        out.println("            font-weight: 700;");
        out.println("            text-transform: uppercase;");
        out.println("            letter-spacing: 1.5px;");
        out.println("            transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);");
        out.println("            box-shadow: 0 10px 30px rgba(168, 85, 247, 0.4);");
        out.println("            position: relative;");
        out.println("            overflow: hidden;");
        out.println("        }");
        out.println("        ");
        out.println("        .retro-button:hover {");
        out.println("            background: linear-gradient(135deg, #ec4899 0%, #a855f7 100%);");
        out.println("            box-shadow: 0 15px 40px rgba(168, 85, 247, 0.5);");
        out.println("            transform: translateY(-3px) scale(1.05);");
        out.println("        }");
        out.println("        ");
        out.println("        .stats-section {");
        out.println("            margin-top: 40px;");
        out.println("            text-align: center;");
        out.println("        }");
        out.println("        ");
        out.println("        .stats-grid {");
        out.println("            display: grid;");
        out.println("            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));");
        out.println("            gap: 20px;");
        out.println("            margin-top: 20px;");
        out.println("        }");
        out.println("        ");
        out.println("        .stat-card {");
        out.println("            background: linear-gradient(135deg, rgba(88, 28, 135, 0.3) 0%, rgba(49, 46, 129, 0.3) 100%);");
        out.println("            border: 1px solid rgba(168, 85, 247, 0.2);");
        out.println("            padding: 32px;");
        out.println("            border-radius: 16px;");
        out.println("            text-align: center;");
        out.println("            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.2);");
        out.println("            backdrop-filter: blur(10px);");
        out.println("            transition: all 0.4s cubic-bezier(0.4, 0, 0.2, 1);");
        out.println("        }");
        out.println("        ");
        out.println("        .stat-card:hover {");
        out.println("            transform: translateY(-8px) scale(1.03);");
        out.println("            box-shadow: 0 20px 40px rgba(168, 85, 247, 0.3);");
        out.println("            border-color: rgba(168, 85, 247, 0.5);");
        out.println("            background: linear-gradient(135deg, rgba(88, 28, 135, 0.5) 0%, rgba(49, 46, 129, 0.5) 100%);");
        out.println("        }");
        out.println("        ");
        out.println("        .stat-number {");
        out.println("            font-size: 3em;");
        out.println("            font-weight: 800;");
        out.println("            background: linear-gradient(135deg, #a855f7 0%, #ec4899 100%);");
        out.println("            -webkit-background-clip: text;");
        out.println("            -webkit-text-fill-color: transparent;");
        out.println("            background-clip: text;");
        out.println("            margin-bottom: 10px;");
        out.println("        }");
        out.println("        ");
        out.println("        .stat-label {");
        out.println("            color: #c4b5fd;");
        out.println("            font-size: 1.1em;");
        out.println("            font-weight: 600;");
        out.println("            letter-spacing: 0.5px;");
        out.println("        }");
        out.println("        ");
        out.println("        .retro-footer {");
        out.println("            text-align: center;");
        out.println("            margin-top: 50px;");
        out.println("            padding-top: 30px;");
        out.println("            border-top: 1px solid rgba(168, 85, 247, 0.2);");
        out.println("            color: #a5b4fc;");
        out.println("            font-size: 0.9em;");
        out.println("        }");
        out.println("    </style>");
        out.println("</head>");
        out.println("<body>");
        out.println("    <div class='retro-container'>");
        out.println("        <h1>" + message + "</h1>");
        out.println("        <p class='welcome-text'>Bienvenue dans le tableau de bord d'analyse de streaming vidéo !</p>");
        out.println("        <p class='welcome-text'>Découvrez les statistiques de vos vidéos préférées en temps réel.</p>");
        out.println("        ");
        out.println("        <div style='text-align: center; margin: 30px 0;'>");
        out.println("            <a href='stats' class='retro-button'>View Statistics</a>");
        out.println("            <a href='dashboard/view' class='retro-button'>Full Dashboard</a>");
        out.println("        </div>");
        out.println("        ");
        out.println("        <div class='stats-section'>");
        out.println("            <h2>Quick Overview</h2>");
        out.println("            <div class='stats-grid'>");
        out.println("                <div class='stat-card'>");
        out.println("                    <div class='stat-number'>100K+</div>");
        out.println("                    <div class='stat-label'>Événements</div>");
        out.println("                </div>");
        out.println("                <div class='stat-card'>");
        out.println("                    <div class='stat-number'>10K+</div>");
        out.println("                    <div class='stat-label'>Vidéos</div>");
        out.println("                </div>");
        out.println("                <div class='stat-card'>");
        out.println("                    <div class='stat-number'>24/7</div>");
        out.println("                    <div class='stat-label'>Analyse</div>");
        out.println("                </div>");
        out.println("            </div>");
        out.println("        </div>");
        out.println("        ");
        out.println("        <div class='retro-footer'>");
        out.println("            <p>Streaming Analytics System - 2025</p>");
        out.println("            <p>Propulsé par Jakarta EE & MongoDB</p>");
        out.println("        </div>");
        out.println("    </div>");
        out.println("</body>");
        out.println("</html>");
    }

    public void destroy() {
    }
}